# requires variable config loading, such as:
# docker stack deploy -c <(docker-compose -f *prod* config) public
#
# also needs an .env file with some variables!

version: '3'
networks:
    proxy:
        external: true
services:
    web:
        image: cjpalmer/public:1.2.3
        volumes:
        - ${LOCAL_ROOT_DIR}:/storage
        - ${LOCAL_LINK_DIR}:/usr/local/apache2/htdocs
        - httpd_users:/usr/local/apache2/auth
        environment:
        - PUBLIC_ROOT_DIR=/storage
        - PUBLIC_LINK_DIR=/usr/local/apache2/htdocs
        - PUBLIC_FQDN_OVERRIDE=https://public.purplebirdman.com
        networks:
        - proxy
volumes:
    httpd_users:
        driver: local
