version: '3'
services:
    app:
        build: .
        image: cliftonpalmer/public
        volumes:
            - /storage:/storage
            - ./public:/root/public
        environment:
            - PUBLIC_ROOT_DIR=/storage/Art/art by me
            - PUBLIC_LINK_DIR=/usr/local/apache2/htdocs/public
            - PUBLIC_HTTP_URI=http://99.198.222.253/public
        ports:
            - 80:80
