version: '3'
services:
    web:
        build: .
        image: cjpalmer/public:1.1.0
        volumes:
        - ${LOCAL_STORAGE}:/storage
        - public_data:/usr/local/apache2/htdocs
        environment:
        - PUBLIC_ROOT_DIR=/storage
        - PUBLIC_LINK_DIR=/usr/local/apache2/htdocs
        - PUBLIC_HTTP_URI=https://${IPV4_WAN}
        ports:
        - 80:80
volumes:
    public_data:
        driver: local
