version: '3'
services:
    web:
        build: .
        image: cjpalmer/public:1.2.0
        volumes:
        - ${SHARE_ROOT}:/storage
        - public_data:/usr/local/apache2/htdocs
        - httpd_users:/usr/local/apache2/auth
        environment:
        - PUBLIC_ROOT_DIR=/storage
        - PUBLIC_LINK_DIR=/usr/local/apache2/htdocs
        ports:
        - 80:80
volumes:
    public_data:
        driver: local
    httpd_users:
        driver: local
