version: '3'
networks:
    default:
        external:
            name: proxy
services:
    web:
        build: .
        image: cliftonpalmer/public
        volumes:
        - ${LOCAL_STORAGE}:/storage
        environment:
        - PUBLIC_ROOT_DIR=/storage/Art/art by me
        - PUBLIC_LINK_DIR=/usr/local/apache2/htdocs
        - PUBLIC_HTTP_URI=http://${IPV4_WAN}
        ports:
        - 80:80
