version: '3'
services:
    app:
        build: .
        image: cliftonpalmer/public
        volumes:
            - ${LOCAL_STORAGE}:/storage
        environment:
            - PUBLIC_ROOT_DIR=/storage/Art/art by me
            - PUBLIC_LINK_DIR=/usr/local/apache2/htdocs/public
            - PUBLIC_HTTP_URI=http://${IPV4_WAN}/public
        ports:
            - 80:80
